# Предобработка текста

Считаем один из файлов и посмотрим, что мы можем с ним сделать

In [3]:
with open("./test.txt") as f:
    example_text = f.read()

example_text

'Получив экземпляр первого издания романа «Алхимик», я испытал искреннюю радость. В течение многих лет читатели-энтузиасты в России пытались распространять книгу самостоятельно – размещали в Интернете, передавали друг другу в виде книжек-самоделок, изготавливали фотокопии текста, который вы сейчас держите в руках. Однако, несмотря на все старания, никак не удавалось, в силу разных обстоятельств, добиться грамотного продвижения «Алхимика» на книжный рынок.\n\nИ вот наконец книгу издали и занялись профессиональным распространением «Алхимика» на российском рынке.\n\nКлючевое понятие, которое лежит в основе повествования о путешествии пастуха Сантьяго,\xa0– это понятие «Своя Судьба». Что же такое Своя Судьба? Это наше высшее предназначение, путь, уготованный нам Господом здесь, на Земле. Всякий раз, когда мы делаем что-то с радостью и удовольствием, это означает, что мы следуем Своей Судьбе. Однако не всем достает мужества идти по этому пути, добиваясь встречи со своей заветной мечтой.\n\n

Токенизация текста - просто выделение оттуда отдельных слов. Обратите внимание, они не приводятся к одному регистру, знаки препинания не удаляются

In [4]:
import nltk
nltk.download('punkt')
tokens = nltk.word_tokenize(example_text)
tokens

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Irina\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


['Получив',
 'экземпляр',
 'первого',
 'издания',
 'романа',
 '«',
 'Алхимик',
 '»',
 ',',
 'я',
 'испытал',
 'искреннюю',
 'радость',
 '.',
 'В',
 'течение',
 'многих',
 'лет',
 'читатели-энтузиасты',
 'в',
 'России',
 'пытались',
 'распространять',
 'книгу',
 'самостоятельно',
 '–',
 'размещали',
 'в',
 'Интернете',
 ',',
 'передавали',
 'друг',
 'другу',
 'в',
 'виде',
 'книжек-самоделок',
 ',',
 'изготавливали',
 'фотокопии',
 'текста',
 ',',
 'который',
 'вы',
 'сейчас',
 'держите',
 'в',
 'руках',
 '.',
 'Однако',
 ',',
 'несмотря',
 'на',
 'все',
 'старания',
 ',',
 'никак',
 'не',
 'удавалось',
 ',',
 'в',
 'силу',
 'разных',
 'обстоятельств',
 ',',
 'добиться',
 'грамотного',
 'продвижения',
 '«',
 'Алхимика',
 '»',
 'на',
 'книжный',
 'рынок',
 '.',
 'И',
 'вот',
 'наконец',
 'книгу',
 'издали',
 'и',
 'занялись',
 'профессиональным',
 'распространением',
 '«',
 'Алхимика',
 '»',
 'на',
 'российском',
 'рынке',
 '.',
 'Ключевое',
 'понятие',
 ',',
 'которое',
 'лежит',
 'в',


Воспользуемся стеммером, чтобы привести слова к одной форме.

In [5]:
from snowballstemmer import RussianStemmer
stemmer = RussianStemmer()
stemmer.stemWords(example_text.lower().split())

['получ',
 'экземпляр',
 'перв',
 'издан',
 'рома',
 '«алхимик»,',
 'я',
 'испыта',
 'искрен',
 'радость.',
 'в',
 'течен',
 'мног',
 'лет',
 'читатели-энтузиаст',
 'в',
 'росс',
 'пыта',
 'распространя',
 'книг',
 'самостоятельн',
 '–',
 'размеща',
 'в',
 'интернете,',
 'передава',
 'друг',
 'друг',
 'в',
 'вид',
 'книжек-самоделок,',
 'изготавлива',
 'фотокоп',
 'текста,',
 'котор',
 'вы',
 'сейчас',
 'держ',
 'в',
 'руках.',
 'однако,',
 'несмотр',
 'на',
 'все',
 'старания,',
 'никак',
 'не',
 'удавалось,',
 'в',
 'сил',
 'разн',
 'обстоятельств,',
 'доб',
 'грамотн',
 'продвижен',
 '«алхимика»',
 'на',
 'книжн',
 'рынок.',
 'и',
 'вот',
 'наконец',
 'книг',
 'изда',
 'и',
 'заня',
 'профессиональн',
 'распространен',
 '«алхимика»',
 'на',
 'российск',
 'рынке.',
 'ключев',
 'понятие,',
 'котор',
 'леж',
 'в',
 'основ',
 'повествован',
 'о',
 'путешеств',
 'пастух',
 'сантьяго,',
 '–',
 'эт',
 'понят',
 '«сво',
 'судьба».',
 'что',
 'же',
 'так',
 'сво',
 'судьба?',
 'эт',
 'наш',


Другой вариант - вместо стеммера использовать лемматизатор - штуку, которая приводит слова к начальной форме.

In [6]:
import pymystem3
mystem = pymystem3.Mystem()
lemm = mystem.lemmatize(' '.join(tokens[:200]))
lemm

['получать',
 ' ',
 'экземпляр',
 ' ',
 'первый',
 ' ',
 'издание',
 ' ',
 'роман',
 ' « ',
 'алхимик',
 ' » , ',
 'я',
 ' ',
 'испытывать',
 ' ',
 'искренний',
 ' ',
 'радость',
 ' ',
 '. ',
 'в',
 ' ',
 'течение',
 ' ',
 'многий',
 ' ',
 'год',
 ' ',
 'читатель',
 '-',
 'энтузиаст',
 ' ',
 'в',
 ' ',
 'россия',
 ' ',
 'пытаться',
 ' ',
 'распространять',
 ' ',
 'книга',
 ' ',
 'самостоятельно',
 ' – ',
 'размещать',
 ' ',
 'в',
 ' ',
 'интернет',
 ' , ',
 'передавать',
 ' ',
 'друг',
 ' ',
 'друг',
 ' ',
 'в',
 ' ',
 'вид',
 ' ',
 'книжка',
 '-',
 'самоделка',
 ' , ',
 'изготовлять',
 ' ',
 'фотокопия',
 ' ',
 'текст',
 ' , ',
 'который',
 ' ',
 'вы',
 ' ',
 'сейчас',
 ' ',
 'держать',
 ' ',
 'в',
 ' ',
 'рука',
 ' ',
 '. ',
 'однако',
 ' , ',
 'несмотря',
 ' ',
 'на',
 ' ',
 'весь',
 ' ',
 'старание',
 ' , ',
 'никак',
 ' ',
 'не',
 ' ',
 'удаваться',
 ' , ',
 'в',
 ' ',
 'сила',
 ' ',
 'разный',
 ' ',
 'обстоятельство',
 ' , ',
 'добиваться',
 ' ',
 'грамотный',
 ' ',
 'продвижение

А еще провести лемматизацию слов можно с помощью морфологического анализатора

In [7]:
import pymorphy2
morph = pymorphy2.MorphAnalyzer()
lemm_pymorph = [morph.parse(s)[0].normal_form for s in tokens]
lemm_pymorph

['получить',
 'экземпляр',
 'первый',
 'издание',
 'роман',
 '«',
 'алхимик',
 '»',
 ',',
 'я',
 'испытать',
 'искренний',
 'радость',
 '.',
 'в',
 'течение',
 'многий',
 'год',
 'читатель-энтузиаст',
 'в',
 'россия',
 'пытаться',
 'распространять',
 'книга',
 'самостоятельно',
 '–',
 'размещать',
 'в',
 'интернет',
 ',',
 'передавать',
 'друг',
 'друг',
 'в',
 'вид',
 'книжка-самоделка',
 ',',
 'изготавливать',
 'фотокопия',
 'текст',
 ',',
 'который',
 'вы',
 'сейчас',
 'держать',
 'в',
 'рука',
 '.',
 'однако',
 ',',
 'несмотря',
 'на',
 'всё',
 'старание',
 ',',
 'никак',
 'не',
 'удаваться',
 ',',
 'в',
 'сила',
 'разный',
 'обстоятельство',
 ',',
 'добиться',
 'грамотный',
 'продвижение',
 '«',
 'алхимик',
 '»',
 'на',
 'книжный',
 'рынок',
 '.',
 'и',
 'вот',
 'наконец',
 'книга',
 'издали',
 'и',
 'заняться',
 'профессиональный',
 'распространение',
 '«',
 'алхимик',
 '»',
 'на',
 'российский',
 'рынок',
 '.',
 'ключевой',
 'понятие',
 ',',
 'который',
 'лежать',
 'в',
 'основа

Чтобы снова собрать из этого, текст, просто сконкатенируем все получившиеся строки:

In [8]:
' '.join(lemm_pymorph)

'получить экземпляр первый издание роман « алхимик » , я испытать искренний радость . в течение многий год читатель-энтузиаст в россия пытаться распространять книга самостоятельно – размещать в интернет , передавать друг друг в вид книжка-самоделка , изготавливать фотокопия текст , который вы сейчас держать в рука . однако , несмотря на всё старание , никак не удаваться , в сила разный обстоятельство , добиться грамотный продвижение « алхимик » на книжный рынок . и вот наконец книга издали и заняться профессиональный распространение « алхимик » на российский рынок . ключевой понятие , который лежать в основа повествование о путешествие пастух сантьяго , – это понятие « свой судьба » . что же такой свой судьба ? это наш высокий предназначение , путь , уготовать мы господь здесь , на земля . всякий раз , когда мы делать что-то с радость и удовольствие , это означать , что мы следуемый свой судьба . однако не весь доставать мужество идти по этот путь , добиваться встреча с свой заветный м

# Формирование выборки сырых данных

Обернем наши предыдущие действия в функцию:

In [11]:
from string import punctuation
import pymorphy2
morph = pymorphy2.MorphAnalyzer()

def lemmatize(input_text):
    tokens = nltk.word_tokenize(input_text)
    normed_tokens = [morph.parse(s)[0].normal_form for s in tokens]
    # исключим также стоп-слова - всякие предлоги, союзы и т.п.
    normed_tokens = [word for word in normed_tokens if word not in nltk.corpus.stopwords.words("russian")]
    # а также знаки препинания
    normed_tokens = [word for word in normed_tokens if word not in punctuation]
    return ' '.join(normed_tokens)

Рассмотрим задачу бинарной классификации текстов. Возьмем 2 текстa книг и попробуем подобрать такой алгоритм, который смог бы их отличать друг от друга.

In [12]:
import os
import pandas as pd

import nltk
nltk.download('stopwords')

# подготовим пустой датафрейм
df = pd.DataFrame(columns=['text', 'class'])

# это папки, в которых лежат файлы с текстами
dir0 = "./little_guy"
dir1 = "./punishment"

# считаем все наши тексты в датафрейм с указанием класса
for filename in os.listdir(dir0):
    with open(os.path.join(dir0, filename),encoding='utf8') as file:   
        contents = lemmatize(file.read())
    df = df.append(pd.Series({'text': contents, 'class': 0}), ignore_index=True)
    
# и для второй папки тоже
for filename in os.listdir(dir1):
    with open(os.path.join(dir1, filename),encoding='utf8') as file:
        contents = lemmatize(file.read())
    df = df.append(pd.Series({'text': contents, 'class': 1}), ignore_index=True)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Irina\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [13]:
df

text class
0   маленький принц i шесть год книга название « п...     0
1   x близкий весь планета маленький принц астерои...     0
2   xi второй планета жить честолюбец — почитатель...     0
3   хii следующий планета жить пьяница маленький п...     0
4   xiii четвёртый планета принадлежать деловой че...     0
..                                                ...   ...
63  `` действительно разумихин недавно ещё хотеть ...     1
64  впоследствии раскольников случиться как-то узн...     1
65  дверь отвориться крошечный щёлочка вострый нед...     1
66  пролежать очень долго случаться просыпаться ми...     1
67  `` обыск застать '' комната никто никто загляд...     1

[68 rows x 2 columns]

Разобьем выборку на трейн и тест

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df['text'], df['class'], test_size=0.3, stratify=df['class'])

## Bag-of-Words-эмбеддинг

Понятное дело, работать с чистым текстом математические методы не умеют. Настало время получить эмбеддинги!

In [15]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
bof_vect = CountVectorizer()
bof_vect.fit(np.hstack([X_train, X_test]))
bof_train = bof_vect.transform(X_train)
bof_test = bof_vect.transform(X_test)

Посмотрим на вид нашего нового признакового пространства

In [16]:
bof_train.toarray()

array([[0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [17]:
bof_train.toarray().shape

(47, 12002)

## TF-IDF-эмбеддинг

In [18]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vect = TfidfVectorizer()
tfidf_vect.fit(np.hstack([X_train, X_test]))
tfidf_train = tfidf_vect.transform(X_train)
tfidf_test = tfidf_vect.transform(X_test)

In [19]:
tfidf_train.toarray()

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.01593842],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [20]:
tfidf_train.toarray().shape

(47, 12002)

## Word2vec-эмбеддинг
Поскольку w2v - это не sklearn'овский классификатор, он на выходе выдаст данные немного другого вида, и это надо будет учитывать в дальнейшей работе

In [21]:
from gensim.models import Word2Vec
X_train_w2v = X_train.apply(str.split)
X_test_w2v = X_test.apply(str.split)
w2v_vect = Word2Vec(np.hstack([X_train_w2v, X_test_w2v]), size=300, min_count=10, workers=8)

In [22]:
X_train_w2v

57    [весь, вечер, десять, час, провести, разный, т...
5     [xiv, пятый, планета, очень, занятный, оказать...
53    [папироска, заговорить, порфирий, петрович, ко...
9     [xviii, маленький, принц, пересечь, пустыня, н...
35    [здоровый, здоровый, весело, крикнуть, навстре...
54    [спешить, свидригайлов, мочь, надеяться, это, ...
13    [xxi, тут-то, появиться, лис, —, здравствуй, —...
16    [хxiv, миновать, неделя, пора, потерпеть, авар...
27    [начало, июль, чрезвычайно, жаркое, время, веч...
17    [xxv, —, человек, забираться, скорый, поезд, п...
23    [vi, маленький, принц, понемногу, понять, такж...
12    [хx, долго, идти, маленький, принц, песок, ска...
26    [ix, понять, решить, странствовать, перелётный...
11    [ii, жить, одиночество, поговорить, душа, шест...
18    [xxvi, неподалёку, колодец, сохраниться, разва...
34    [озаботить, серьёзный, проснуться, разумихин, ...
31    [выйти, встать, заложить, крючок, дверь, развя...
42    [главное, дело, последний, минута, никак, 

Преобразуем тексты произведений в вектора - возьмем сумму векторов всех слов, которые входят в прозу

In [23]:
import numpy as np

def text2vec(text):
    """Усредняем векторы слов"""
    vecs = []
    for word in text:
        try:
            vecs.append(w2v_vect[word])
        except KeyError:
            pass
    return np.sum(vecs, axis=0) / len(vecs)

w2v_train = X_train_w2v.apply(text2vec)
w2v_test = X_test_w2v.apply(text2vec)
w2v_train

<ipython-input-23-c817aeec8a46>:8: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  vecs.append(w2v_vect[word])


57    [-0.010966268, -0.19642776, -0.15400949, 0.160...
5     [0.0239139, -0.17394106, -0.21006007, 0.110992...
53    [-0.01141335, -0.20530544, -0.1607142, 0.16761...
9     [0.03885354, -0.17263985, -0.24157633, 0.09470...
35    [-0.011503428, -0.21043126, -0.16428047, 0.171...
54    [-0.010707934, -0.20916077, -0.16553909, 0.170...
13    [0.03280443, -0.16863061, -0.2242568, 0.097972...
16    [0.015357481, -0.18459915, -0.20034596, 0.1265...
27    [-0.011412908, -0.19999173, -0.15624836, 0.163...
17    [0.022438392, -0.17609249, -0.2082436, 0.11356...
23    [0.00950568, -0.185874, -0.1892982, 0.13277794...
12    [0.018591167, -0.17148457, -0.19661336, 0.1136...
26    [0.017677208, -0.17779638, -0.19906552, 0.1191...
11    [0.0106609315, -0.17407155, -0.18065007, 0.123...
18    [0.012945451, -0.18495204, -0.19551872, 0.1293...
34    [-0.011457428, -0.20925252, -0.16280709, 0.170...
31    [-0.011799119, -0.20446031, -0.15965313, 0.167...
42    [-0.011397906, -0.2102867, -0.16452438, 0.

In [24]:
w2v_train.shape

(47,)

## Классификация текстов

Теперь у нас есть классическое признаковое описание каждого текста. Можем обучать классификаторы или придумать еще какую-то метрику.

Давайте вычислим для каждого эмбеддинга по два суммарных вектора - для текстов Куприна и для текстов Коэльо. Для Bag of Words:

In [63]:
little_guy_mean_bof = np.sum(bof_train[y_train == 0], axis=0)
little_guy_mean_bof.shape

(1, 12002)

In [64]:
punishment_mean_bof = np.sum(bof_train[y_train == 1], axis=0)
punishment_mean_bof.shape

(1, 12002)

Для TF-IDF

In [66]:
little_guy_mean_tfidf = np.sum(tfidf_train[y_train == 0], axis=0)
little_guy_mean_tfidf.shape

(1, 12002)

In [67]:
punishment_mean_tfidf = np.sum(tfidf_train[y_train == 1], axis=0)

Для Word2Vec

In [68]:
little_guy_mean_w2v = np.sum(w2v_train[y_train == 0], axis=0)
little_guy_mean_w2v.shape
punishment_mean_w2v = np.sum(w2v_train[y_train == 1], axis=0)

Посмотрим на их вид:

In [69]:
little_guy_mean_bof

matrix([[0, 0, 0, ..., 0, 3, 1]], dtype=int64)

In [70]:
punishment_mean_tfidf

matrix([[0.        , 0.        , 0.        , ..., 0.        , 0.01948601,
         0.01593842]])

In [71]:
little_guy_mean_w2v

array([ 3.7092787e-01, -3.3302915e+00, -3.8257163e+00,  2.1971252e+00,
        9.8315662e-01, -1.7760329e+00,  2.7130105e+00,  1.6216923e+00,
       -2.4020629e+00, -1.3693084e+00,  1.1908207e+00, -1.9335695e-01,
        4.9617081e+00,  1.0360515e+00, -3.7746994e+00,  1.6549693e+00,
        1.7334353e+00, -2.3942342e+00, -5.5022607e+00, -1.0688537e+00,
        5.0580993e-02, -1.1330364e+00,  5.7979301e-02,  9.2752957e-01,
       -2.4605331e+00,  2.5706995e+00, -9.1845101e-01, -2.0660360e-01,
        7.4275637e-01,  1.1011337e-01, -4.7563696e+00,  3.9813747e+00,
        8.3535177e-01, -2.3539448e-01,  3.0421585e-01, -3.6390715e+00,
       -4.3951068e+00,  1.7787704e+00,  2.0127912e+00, -4.3204457e-01,
       -1.9493415e+00, -1.3371359e+00, -1.4039849e-01, -1.7517266e+00,
       -5.0576258e+00, -2.8715527e+00, -2.7435389e+00,  3.2809240e-01,
       -3.6172409e+00,  5.6449542e+00,  4.9087489e-01,  9.6343809e-01,
        2.7081091e+00,  3.9733531e+00,  6.2350434e-01, -2.1371117e+00,
      

А теперь построим датафреймы с результатами классификации тестовых текстов. Будем считать, что текст относится к тому произведению, с которым его косинусное расстояние больше.

In [72]:
from scipy.spatial.distance import cosine
bof_little_guy = np.apply_along_axis(cosine, 1, bof_test.toarray(), v=little_guy_mean_bof)
bof_punishment = np.apply_along_axis(cosine, 1, bof_test.toarray(), v=punishment_mean_bof)

print(np.maximum(bof_little_guy,bof_punishment)==bof_little_guy)

bof_results = pd.DataFrame([
    bof_little_guy,
    bof_punishment,
    np.maximum(bof_little_guy, bof_punishment)==bof_little_guy,   
    y_test
], index=["little_guy", "punishment", "predict", "class"]).T.astype(np.float)
bof_results



[False  True False  True False  True  True  True  True False  True  True
 False False False  True  True  True  True False  True]


little_guy  punishment  predict  class
0     0.347993    0.646712      0.0    0.0
1     0.533236    0.234699      1.0    1.0
2     0.382146    0.708942      0.0    0.0
3     0.484417    0.192325      1.0    1.0
4     0.387089    0.624223      0.0    0.0
5     0.705058    0.439003      1.0    1.0
6     0.522856    0.162715      1.0    1.0
7     0.471950    0.200783      1.0    1.0
8     0.588303    0.316510      1.0    1.0
9     0.604912    0.888734      0.0    0.0
10    0.572460    0.225324      1.0    1.0
11    0.616911    0.332559      1.0    1.0
12    0.439595    0.575302      0.0    0.0
13    0.427376    0.560337      0.0    0.0
14    0.590969    0.823630      0.0    0.0
15    0.541917    0.223553      1.0    1.0
16    0.535108    0.157590      1.0    1.0
17    0.528255    0.240016      1.0    1.0
18    0.504568    0.170118      1.0    1.0
19    0.396781    0.569009      0.0    0.0
20    0.532076    0.212325      1.0    1.0

И посчитаем accuracy для предсказаний

In [73]:
from sklearn.metrics import accuracy_score
accuracy_score(bof_results['predict'], bof_results['class'])

1.0

In [74]:
tfidf_little_guy = np.apply_along_axis(cosine, 1, tfidf_test.toarray(), v=little_guy_mean_tfidf)
tfidf_punishment = np.apply_along_axis(cosine, 1, tfidf_test.toarray(), v=punishment_mean_tfidf)

tfidf_results = pd.DataFrame([
    tfidf_little_guy,
    tfidf_punishment,
    np.maximum(tfidf_little_guy, tfidf_punishment) == tfidf_little_guy,
    y_test
], index=["little_guy", "punishment", "predict", "class"]).T.astype(np.float)
tfidf_results

little_guy  punishment  predict  class
0     0.640919    0.844060      0.0    0.0
1     0.778922    0.444013      1.0    1.0
2     0.683053    0.888736      0.0    0.0
3     0.742740    0.431957      1.0    1.0
4     0.608607    0.818161      0.0    0.0
5     0.876633    0.609593      1.0    1.0
6     0.767429    0.378562      1.0    1.0
7     0.729716    0.395510      1.0    1.0
8     0.791935    0.532689      1.0    1.0
9     0.778348    0.941509      0.0    0.0
10    0.803985    0.435784      1.0    1.0
11    0.818683    0.547491      1.0    1.0
12    0.621076    0.811592      0.0    0.0
13    0.693826    0.801926      0.0    0.0
14    0.777539    0.921521      0.0    0.0
15    0.795778    0.471945      1.0    1.0
16    0.771694    0.376506      1.0    1.0
17    0.758545    0.468622      1.0    1.0
18    0.751462    0.331002      1.0    1.0
19    0.663101    0.815769      0.0    0.0
20    0.776281    0.430090      1.0    1.0

In [75]:
accuracy_score(tfidf_results['predict'], tfidf_results['class'])

1.0

In [76]:
w2v_little_guy = np.apply_along_axis(cosine, 0, w2v_test, v=little_guy_mean_w2v)
w2v_punishment = np.apply_along_axis(cosine, 0, w2v_test, v=punishment_mean_w2v)

w2v_results = pd.DataFrame([
    w2v_little_guy,
    w2v_punishment,
    np.maximum(w2v_little_guy, w2v_punishment) == w2v_little_guy,
    y_test
], index=["little_guy", "punishment", "predict", "class"]).T.astype(np.float)
w2v_results

ValueError: operands could not be broadcast together with shapes (21,) (300,) 

In [ ]:
accuracy_score(w2v_results['predict'], w2v_results['class'])

In [77]:
from sklearn.ensemble import RandomForestClassifier
RandomForestClassifier().fit(bof_train.toarray(), y_train.tolist()).score(bof_test.toarray(), y_test.tolist())

1.0

In [78]:
RandomForestClassifier().fit(tfidf_train.toarray(), y_train.tolist()).score(tfidf_test.toarray(), y_test.tolist())

1.0

In [79]:
RandomForestClassifier().fit(w2v_train.T, y_train.tolist()).score(w2v_test.T, y_test.tolist())

ValueError: setting an array element with a sequence.